### ISSUE TITLE
How to send messages

### ISSUE THREAD

**Issue by DavidLinhares-DV** [nus/dart_mavlink#4]
Hey, thanks for this lib, 
I was able to make your example run without any issue, but i might be missing something i can't find how to send messages.

Could you help me by providing an example or even show me where i could find those informations ?

**Comment by nus** [comment]
Thanks for using this library!

I added an example of requesting parameters.
https://github.com/nus/dart_mavlink/blob/main/example/parameter.dart

**Comment by DavidLinhares-DV** [comment]
Awesome!

I tested the solution with a CommandLong and MAV_CMD_DO_FLIGHTTERMINATION in simulation, and it worked perfectly.

Thank you so much for your help and quick response. I really appreciate it!

**Comment by Gocrackit** [comment]
I am not able to change the mode. Can anyone please help me out how to change the mode.

My code
`  var changeMode=SetMode(customMode: 216, targetSystem: 1, baseMode: 88);
      var frm = MavlinkFrame.v1(sequence, systemId, componentId, paramRequestList);
      socket.send(frm.serialize(), d.address, d.port);`
